name: Deployment Approval
on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
      group-id:
        type: string
        required: true
      group-name:
        type: string
        required: true
      approve-url:
        type: string
        required: true
      reject-url:
        type: string
        required: true

jobs:
  test:
    name: Send Approvals
    runs-on: [ubuntu-latest]
    steps:
    - run: |
        echo "# $GROUP_NAME Approvals for \`$ENVIRONMENT\`" >> $GITHUB_STEP_SUMMARY
        echo "* [Approve]($APPROVE_URL)" >> $GITHUB_STEP_SUMMARY
        echo "* [Reject]($REJECT_URL)" >> $GITHUB_STEP_SUMMARY
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        GROUP_ID: ${{ inputs.group-id }}
        GROUP_NAME: ${{ inputs.group-name }}
        APPROVE_URL: ${{ inputs.approve-url }}
        REJECT_URL: ${{ inputs.reject-url }}
